// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "gitdc.ee.guardtime.com/alphabill/alphabill/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// StateProcessor is an autogenerated mock type for the StateProcessor type
type StateProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: payment
func (_m *StateProcessor) Process(payment *domain.PaymentOrder) error {
	ret := _m.Called(payment)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.PaymentOrder) error); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
