// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	state "gitdc.ee.guardtime.com/alphabill/alphabill/internal/state"
)

// StateProcessor is an autogenerated mock type for the StateProcessor type
type StateProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: tx
func (_m *StateProcessor) Process(tx state.GenericTransaction) error {
	ret := _m.Called(tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(state.GenericTransaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
