// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	state "gitdc.ee.guardtime.com/alphabill/alphabill/internal/txsystem/state"
	uint256 "github.com/holiman/uint256"
	mock "github.com/stretchr/testify/mock"
)

// StateTree is an autogenerated mock type for the StateTree type
type StateTree struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: id, owner, data, stateHash
func (_m *StateTree) AddItem(id *uint256.Int, owner state.Predicate, data state.UnitData, stateHash []byte) error {
	ret := _m.Called(id, owner, data, stateHash)

	var r0 error
	if rf, ok := ret.Get(0).(func(*uint256.Int, state.Predicate, state.UnitData, []byte) error); ok {
		r0 = rf(id, owner, data, stateHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBlockNumber provides a mock function with given fields:
func (_m *StateTree) GetBlockNumber() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// GetRootHash provides a mock function with given fields:
func (_m *StateTree) GetRootHash() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}
