FROM amazonlinux:2

# Update package manager repositories
RUN yum update -y && yum install -y initscripts;
CMD ["/usr/sbin/init"]

# Install make
RUN yum install -y make

# Install go (gcc needed for some go libraries)
RUN yum install -y tar gcc
RUN curl -SL https://golang.org/dl/go1.18.1.linux-amd64.tar.gz | tar -xzC /usr/local
ENV PATH=/usr/local/go/bin:$PATH

# Install trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.34.0
RUN curl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl > html.tpl

# Install nancy
RUN curl -sL https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.42/nancy-v1.0.42-linux-amd64 -o /usr/local/bin/nancy
RUN chmod +x /usr/local/bin/nancy

# Install gosec
RUN curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b /usr/local/go/bin v2.14.0

# Install git
RUN yum install -y git

# Post-install cleanup
RUN yum clean all
RUN rm -rf /var/cache/yum

# Set Go specific env variables
ENV GOPATH=/usr/local/go

# Install cobertura
RUN go install github.com/boumenot/gocover-cobertura@v1.2.0

COPY go.mod go.sum ./
RUN go mod download
RUN rm ./go.mod ./go.sum
