FROM amazonlinux:2

# Update package manager repositories
RUN yum update -y && yum install -y initscripts;
CMD ["/usr/sbin/init"]

# Install make
RUN yum install -y make

# Install go (gcc needed for some go libraries)
RUN yum install -y tar gcc
RUN curl -SL https://golang.org/dl/go1.18.1.linux-amd64.tar.gz | tar -xzC /usr/local
ENV PATH=/usr/local/go/bin:$PATH

# Install trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.26.0
RUN curl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl > html.tpl

# Install nancy
RUN curl -sL https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.33/nancy-v1.0.33-linux-amd64 -o /usr/local/bin/nancy
RUN chmod +x /usr/local/bin/nancy

# Install gosec
RUN curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b /usr/local/go/bin v2.11.0

# Install git
RUN yum install -y git

# Install python and activate virtual env
RUN yum install -y python3
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN python3 -m pip install --upgrade pip

# Set repo access token (for faucet to access alphabill repo)
# The access token is defined in https://gitdc.ee.guardtime.com/alphabill/alphabill/-/settings/ci_cd under Variables
RUN git config --global url."https://token:glpat-ERLQPJ5LG11pfJcychvP@gitdc.ee.guardtime.com/alphabill/alphabill".insteadOf "https://gitdc.ee.guardtime.com/alphabill/alphabill"

# Install Hashicorp Levant
RUN yum -y install unzip
RUN curl -L https://releases.hashicorp.com/levant/0.3.0/levant_0.3.0_linux_amd64.zip -o /tmp/levant.zip
RUN unzip -d /usr/bin/ /tmp/levant.zip
RUN chmod +x /usr/bin/levant
RUN rm /tmp/levant.zip

# Install python requirements
COPY deployments/gitlab/python-requirements.txt /tmp/python-requirements.txt
RUN python3 -m pip install -r /tmp/python-requirements.txt
RUN rm /tmp/python-requirements.txt

# Post-install cleanup
RUN yum clean all
RUN rm -rf /var/cache/yum

# Set Go specific env variables
ENV GOPATH=/usr/local/go

# Install cobertura
RUN go install github.com/boumenot/gocover-cobertura@v1.2.0
