FROM amazonlinux:2

# Update package manager repositories
RUN yum update -y && yum install -y initscripts;
CMD ["/usr/sbin/init"]

# Install make
RUN yum install -y make

# Install go (gcc needed for some go libraries)
RUN yum install -y tar gcc
RUN curl -SL https://golang.org/dl/go1.18.linux-amd64.tar.gz | tar -xzC /usr/local
ENV PATH=/usr/local/go/bin:$PATH

# Install trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.19.2
RUN curl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl > html.tpl

# Install nancy
RUN curl -sL https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.22/nancy-v1.0.22-linux-amd64 -o /usr/local/bin/nancy
RUN chmod +x /usr/local/bin/nancy

# Install gosec
RUN curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b /usr/local/go/bin v2.8.1

# Post-install cleanup
RUN yum clean all
RUN rm -rf /var/cache/yum

# Set Go specific env variables
ENV GOPATH=/usr/local/go

# Install cobertura
RUN go install github.com/boumenot/gocover-cobertura@v1.2.0
