services:
  alphabill:
    platform: linux/amd64
    user: root
    build:
      context: ./
      dockerfile: ./scripts/Dockerfile

  alphabill-root-genesis:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - root:/genesis/root
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Creating root genesis..." && \
        alphabill root-node init \
          --home /genesis/root \
          --generate && \
        echo "Creating root trust base..." && \
        alphabill trust-base generate \
          --home /genesis \
          --network-id 3 \
          --node-info /genesis/root/node-info.json &&  \
        echo "Signing root trust base..." && \
        alphabill trust-base sign \
          --home /genesis/root \
          --trust-base /genesis/trust-base.json

  alphabill-money-genesis:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - money:/genesis/money
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Creating money genesis..." && \
        alphabill shard-node init \
          --home /genesis/money \
          --generate && \
        echo "Creating money partition configuration..." && \
        alphabill shard-conf generate \
          --home /genesis \
          --network-id 3 \
          --partition-id 1 \
          --partition-type-id 1 \
          --epoch-start 10 \
          --initial-bill-owner-predicate 0x830041025820786C9F82FCD2CFB4190A690725E85734F2D25B86DBC35186D85D08F3CFC2B7CA \
          --node-info=/genesis/money/node-info.json && \
        echo "Creating money partition state..." && \
        alphabill shard-conf genesis \
          --home /genesis/money \
          --shard-conf /genesis/shard-conf-1_0.json

  alphabill-tokens-genesis:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - tokens:/genesis/tokens
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Creating tokens genesis..." && \
        alphabill shard-node init \
          --home /genesis/tokens --generate && \
        echo "Creating tokens partition configuration..." && \
        alphabill shard-conf generate \
          --home /genesis \
          --network-id 3 \
          --partition-id 2 \
          --partition-type-id 2 \
          --epoch-start 10 \
          --node-info=/genesis/tokens/node-info.json && \
        echo "Creating tokens partition state..." && \
        alphabill shard-conf genesis \
          --home /genesis/tokens \
          --shard-conf /genesis/shard-conf-2_0.json

  alphabill-permissioned-tokens-genesis:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - permissioned-tokens:/genesis/permissioned-tokens
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Creating permissioned tokens genesis..." && \
        alphabill shard-node init \
          --home /genesis/permissioned-tokens \
          --generate && \
        echo "Creating permissioned tokens partition configuration..." && \
        alphabill shard-conf generate \
          --home /genesis \
          --network-id 3 \
          --partition-id 5 \
          --partition-type-id 2 \
          --epoch-start 10 \
          --feeless-mode true \
          --admin-owner-predicate 0x830041025820786C9F82FCD2CFB4190A690725E85734F2D25B86DBC35186D85D08F3CFC2B7CA \
          --node-info=/genesis/permissioned-tokens/node-info.json && \
        echo "Creating permissioned tokens partition state..." && \
        alphabill shard-conf genesis \
          --home "/genesis/permissioned-tokens" \
          --shard-conf /genesis/shard-conf-5_0.json

  alphabill-root:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - root:/genesis/root
    depends_on:
      alphabill-root-genesis:
        condition: service_completed_successfully
      alphabill-money-genesis:
        condition: service_completed_successfully
      alphabill-tokens-genesis:
        condition: service_completed_successfully
      alphabill-permissioned-tokens-genesis:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "nc", "-zv", "alphabill-root", "8000" ]
      interval: 5s
    networks:
      - default
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Starting root node..." && \
        alphabill root-node run \
          --home /genesis/root \
          --shard-conf=/genesis/shard-conf-1_0.json \
          --shard-conf=/genesis/shard-conf-2_0.json \
          --shard-conf=/genesis/shard-conf-5_0.json \
          --address "/ip4/$(hostname -i)/tcp/8000" \
          --trust-base /genesis/trust-base.json \
          --rpc-server-address "$(hostname -i):8002"

  alphabill-money:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - root:/genesis/root
      - money:/genesis/money
    depends_on:
      alphabill-money-genesis:
        condition: service_completed_successfully
      alphabill-root:
        condition: service_healthy
    ports:
      - "9003:9003"
    healthcheck:
      test: [ "CMD", "nc", "-zv", "alphabill-money", "9001" ]
      interval: 2s
    networks:
      - default
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Starting money partition..." && \
        alphabill shard-node run \
          --home /genesis/money \
          --trust-base /genesis/trust-base.json \
          --shard-conf /genesis/shard-conf-1_0.json \
          --address "/ip4/$(hostname -i)/tcp/9001" \
          --bootnodes "/dns/alphabill-root/tcp/8000/p2p/$(alphabill node-id --home /genesis/root | tail -n1)" \
          --rpc-server-address "$(hostname -i):9003"

  alphabill-tokens:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - root:/genesis/root
      - tokens:/genesis/tokens
    depends_on:
      alphabill-tokens-genesis:
        condition: service_completed_successfully
      alphabill-root:
        condition: service_healthy
    ports:
      - "10003:10003"
    healthcheck:
      test: [ "CMD", "nc", "-zv", "alphabill-tokens", "10001" ]
      interval: 2s
    networks:
      - default
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Starting tokens partition..." && \
        alphabill shard-node run \
          --home "/genesis/tokens" \
          --trust-base /genesis/trust-base.json \
          --shard-conf /genesis/shard-conf-2_0.json \
          --address "/ip4/$(hostname -i)/tcp/10001" \
          --bootnodes "/dns/alphabill-root/tcp/8000/p2p/$(alphabill node-id --home /genesis/root | tail -n1)" \
          --rpc-server-address "$(hostname -i):10003"

  alphabill-permissioned-tokens:
    extends:
      service: alphabill
    volumes:
      - genesis:/genesis
      - root:/genesis/root
      - permissioned-tokens:/genesis/permissioned-tokens
    depends_on:
      alphabill-permissioned-tokens-genesis:
        condition: service_completed_successfully
      alphabill-root:
        condition: service_healthy
    ports:
      - "11003:11003"
    healthcheck:
      test: [ "CMD", "nc", "-zv", "alphabill-permissioned-tokens", "11001" ]
      interval: 2s
    networks:
      - default
    entrypoint: [ "/busybox/sh", "-c" ]
    command:
      - |
        echo "Starting permissioned tokens partition..." && \
        alphabill shard-node run \
          --home /genesis/permissioned-tokens \
          --trust-base /genesis/trust-base.json \
          --shard-conf /genesis/shard-conf-5_0.json \
          --address "/ip4/$(hostname -i)/tcp/11001" \
          --bootnodes "/dns/alphabill-root/tcp/8000/p2p/$(alphabill node-id --home /genesis/root | tail -n1)" \
          --rpc-server-address "$(hostname -i):11003"

networks:
  default:

volumes:
  genesis:
  root:
  money:
  tokens:
  permissioned-tokens:
