services:
  alphabill:
    build:
      context: ./
      dockerfile: ./cli/alphabill/Dockerfile
  alphabill-root:
    extends:
      service: alphabill
    entrypoint:
      - /busybox/sh
      - -c
      - 'alphabill root --home /genesis --address="/ip4/$(hostname -i)/tcp/8000" --log-level warn --bootnodes=$(alphabill identifier -k /genesis-nodes/root1/rootchain/keys.json | tail -n1)@/dns/alphabill-root1/tcp/8000,$(alphabill identifier -k /genesis-nodes/root2/rootchain/keys.json | tail -n1)@/dns/alphabill-root2/tcp/8000,$(alphabill identifier -k /genesis-nodes/root3/rootchain/keys.json | tail -n1)@/dns/alphabill-root3/tcp/8000'
    expose:
      - 8000
  alphabill-money:
    extends:
      service: alphabill
    entrypoint:
      - /busybox/sh
      - -c
      - 'alphabill money --home /genesis/money --address="/ip4/$(hostname -i)/tcp/8000" --log-level warn  --rpc-server-address=$(hostname -i):8001 --server-address $(hostname -i):8002 --key-file /genesis/money/keys.json --genesis /genesis-nodes/root1/rootchain/partition-genesis-1.json --state /genesis/money/node-genesis-state.cbor --db /genesis/blocks.db --tx-db /genesis/tx.db --bootnodes=$(alphabill identifier -k /genesis-nodes/root1/rootchain/keys.json | tail -n1)@/dns/alphabill-root1/tcp/8000,$(alphabill identifier -k /genesis-nodes/root2/rootchain/keys.json | tail -n1)@/dns/alphabill-root2/tcp/8000,$(alphabill identifier -k /genesis-nodes/root3/rootchain/keys.json | tail -n1)@/dns/alphabill-root3/tcp/8000'
    expose:
      - 8000
  alphabill-tokens:
    extends:
      service: alphabill
    entrypoint:
      - /busybox/sh
      - -c
      - 'alphabill tokens --home /genesis/tokens --address="/ip4/$(hostname -i)/tcp/8000" --log-level warn --rpc-server-address=$(hostname -i):8001 --server-address $(hostname -i):8002 --key-file /genesis/tokens/keys.json --genesis /genesis-nodes/root1/rootchain/partition-genesis-2.json --state /genesis/tokens/node-genesis-state.cbor --db /genesis/blocks.db --tx-db /genesis/tx.db --bootnodes=$(alphabill identifier -k /genesis-nodes/root1/rootchain/keys.json | tail -n1)@/dns/alphabill-root1/tcp/8000,$(alphabill identifier -k /genesis-nodes/root2/rootchain/keys.json | tail -n1)@/dns/alphabill-root2/tcp/8000,$(alphabill identifier -k /genesis-nodes/root3/rootchain/keys.json | tail -n1)@/dns/alphabill-root3/tcp/8000'
    expose:
      - 8000
  generate-tokens-genesis:
    extends:
      service: alphabill
    entrypoint:
      - alphabill
      - tokens-genesis
      - -g
      - --home
      - /genesis
  generate-money-genesis:
    extends:
      service: alphabill
    entrypoint:
      - alphabill
      - money-genesis
      - -g
      - --home
      - /genesis
  generate-root-genesis:
    extends:
      service: alphabill
    entrypoint:
      - alphabill
      - root-genesis
      - new
      - -g
      - --block-rate
      - "400"
      - --consensus-timeout
      - "2500"
      - --total-nodes
      - "3"
      - --home
      - /genesis
      - -p
      - /genesis-nodes/money1/money/node-genesis.json
      - -p
      - /genesis-nodes/money2/money/node-genesis.json
      - -p
      - /genesis-nodes/money3/money/node-genesis.json
      - -p
      - /genesis-nodes/tokens1/tokens/node-genesis.json
      - -p
      - /genesis-nodes/tokens2/tokens/node-genesis.json
      - -p
      - /genesis-nodes/tokens3/tokens/node-genesis.json
    volumes:
      - ./.genesis:/genesis-nodes
  combine-root-genesis:
    extends:
      service: alphabill
    entrypoint:
      - alphabill
      - root-genesis
      - combine
      - --home
      - /genesis/root
      - --root-genesis=/genesis/root1/rootchain/root-genesis.json
      - --root-genesis=/genesis/root2/rootchain/root-genesis.json
      - --root-genesis=/genesis/root3/rootchain/root-genesis.json
    volumes:
      - ./.genesis:/genesis