// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpcab

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlphaBillServiceClient is the client API for AlphaBillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlphaBillServiceClient interface {
	SyncBlocks(ctx context.Context, in *SyncBlocksRequest, opts ...grpc.CallOption) (AlphaBillService_SyncBlocksClient, error)
}

type alphaBillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlphaBillServiceClient(cc grpc.ClientConnInterface) AlphaBillServiceClient {
	return &alphaBillServiceClient{cc}
}

func (c *alphaBillServiceClient) SyncBlocks(ctx context.Context, in *SyncBlocksRequest, opts ...grpc.CallOption) (AlphaBillService_SyncBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &AlphaBillService_ServiceDesc.Streams[0], "/rpc.AlphaBillService/SyncBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &alphaBillServiceSyncBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AlphaBillService_SyncBlocksClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type alphaBillServiceSyncBlocksClient struct {
	grpc.ClientStream
}

func (x *alphaBillServiceSyncBlocksClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AlphaBillServiceServer is the server API for AlphaBillService service.
// All implementations must embed UnimplementedAlphaBillServiceServer
// for forward compatibility
type AlphaBillServiceServer interface {
	SyncBlocks(*SyncBlocksRequest, AlphaBillService_SyncBlocksServer) error
	mustEmbedUnimplementedAlphaBillServiceServer()
}

// UnimplementedAlphaBillServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlphaBillServiceServer struct {
}

func (UnimplementedAlphaBillServiceServer) SyncBlocks(*SyncBlocksRequest, AlphaBillService_SyncBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncBlocks not implemented")
}
func (UnimplementedAlphaBillServiceServer) mustEmbedUnimplementedAlphaBillServiceServer() {}

// UnsafeAlphaBillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlphaBillServiceServer will
// result in compilation errors.
type UnsafeAlphaBillServiceServer interface {
	mustEmbedUnimplementedAlphaBillServiceServer()
}

func RegisterAlphaBillServiceServer(s grpc.ServiceRegistrar, srv AlphaBillServiceServer) {
	s.RegisterService(&AlphaBillService_ServiceDesc, srv)
}

func _AlphaBillService_SyncBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlphaBillServiceServer).SyncBlocks(m, &alphaBillServiceSyncBlocksServer{stream})
}

type AlphaBillService_SyncBlocksServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type alphaBillServiceSyncBlocksServer struct {
	grpc.ServerStream
}

func (x *alphaBillServiceSyncBlocksServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

// AlphaBillService_ServiceDesc is the grpc.ServiceDesc for AlphaBillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlphaBillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AlphaBillService",
	HandlerType: (*AlphaBillServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncBlocks",
			Handler:       _AlphaBillService_SyncBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "alphabill.proto",
}
