// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ComponentStarter is an autogenerated mock type for the ComponentStarter type
type ComponentStarter struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx
func (_m *ComponentStarter) Start(ctx context.Context) {
	_m.Called(ctx)
}
