// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: atomic_broadcast.proto

package atomic_broadcast

import (
	certificates "github.com/alphabill-org/alphabill/internal/certificates"
	certification "github.com/alphabill-org/alphabill/internal/network/protocol/certification"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificationReqWithProof_CERT_REASON int32

const (
	CertificationReqWithProof_QUORUM              CertificationReqWithProof_CERT_REASON = 0
	CertificationReqWithProof_QUORUM_NOT_POSSIBLE CertificationReqWithProof_CERT_REASON = 1
	CertificationReqWithProof_T2_TIMEOUT          CertificationReqWithProof_CERT_REASON = 2
)

// Enum value maps for CertificationReqWithProof_CERT_REASON.
var (
	CertificationReqWithProof_CERT_REASON_name = map[int32]string{
		0: "QUORUM",
		1: "QUORUM_NOT_POSSIBLE",
		2: "T2_TIMEOUT",
	}
	CertificationReqWithProof_CERT_REASON_value = map[string]int32{
		"QUORUM":              0,
		"QUORUM_NOT_POSSIBLE": 1,
		"T2_TIMEOUT":          2,
	}
)

func (x CertificationReqWithProof_CERT_REASON) Enum() *CertificationReqWithProof_CERT_REASON {
	p := new(CertificationReqWithProof_CERT_REASON)
	*p = x
	return p
}

func (x CertificationReqWithProof_CERT_REASON) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificationReqWithProof_CERT_REASON) Descriptor() protoreflect.EnumDescriptor {
	return file_atomic_broadcast_proto_enumTypes[0].Descriptor()
}

func (CertificationReqWithProof_CERT_REASON) Type() protoreflect.EnumType {
	return &file_atomic_broadcast_proto_enumTypes[0]
}

func (x CertificationReqWithProof_CERT_REASON) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificationReqWithProof_CERT_REASON.Descriptor instead.
func (CertificationReqWithProof_CERT_REASON) EnumDescriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{0, 0}
}

type StateReplyMsg_Status int32

const (
	// All ok, latest included in reply
	StateReplyMsg_OK StateReplyMsg_Status = 0
	// invalid state hash (in the future)
	StateReplyMsg_UNKNOWN_STATE StateReplyMsg_Status = 1
)

// Enum value maps for StateReplyMsg_Status.
var (
	StateReplyMsg_Status_name = map[int32]string{
		0: "OK",
		1: "UNKNOWN_STATE",
	}
	StateReplyMsg_Status_value = map[string]int32{
		"OK":            0,
		"UNKNOWN_STATE": 1,
	}
)

func (x StateReplyMsg_Status) Enum() *StateReplyMsg_Status {
	p := new(StateReplyMsg_Status)
	*p = x
	return p
}

func (x StateReplyMsg_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateReplyMsg_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_atomic_broadcast_proto_enumTypes[1].Descriptor()
}

func (StateReplyMsg_Status) Type() protoreflect.EnumType {
	return &file_atomic_broadcast_proto_enumTypes[1]
}

func (x StateReplyMsg_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateReplyMsg_Status.Descriptor instead.
func (StateReplyMsg_Status) EnumDescriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{15, 0}
}

type CertificationReqWithProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// system identifier of the input record changed
	SystemIdentifier []byte                                `protobuf:"bytes,1,opt,name=system_identifier,json=systemIdentifier,proto3" json:"system_identifier,omitempty"`
	CertReason       CertificationReqWithProof_CERT_REASON `protobuf:"varint,2,opt,name=certReason,proto3,enum=CertificationReqWithProof_CERT_REASON" json:"certReason,omitempty"`
	// IR change (quorum or no quorum possible of block certification requests)
	Requests []*certification.BlockCertificationRequest `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *CertificationReqWithProof) Reset() {
	*x = CertificationReqWithProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificationReqWithProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificationReqWithProof) ProtoMessage() {}

func (x *CertificationReqWithProof) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificationReqWithProof.ProtoReflect.Descriptor instead.
func (*CertificationReqWithProof) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *CertificationReqWithProof) GetSystemIdentifier() []byte {
	if x != nil {
		return x.SystemIdentifier
	}
	return nil
}

func (x *CertificationReqWithProof) GetCertReason() CertificationReqWithProof_CERT_REASON {
	if x != nil {
		return x.CertReason
	}
	return CertificationReqWithProof_QUORUM
}

func (x *CertificationReqWithProof) GetRequests() []*certification.BlockCertificationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// IR change requests with quorum or no quorum possible
	Requests []*CertificationReqWithProof `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetRequests() []*CertificationReqWithProof {
	if x != nil {
		return x.Requests
	}
	return nil
}

// The ConsensusInfo is used both in VoteMsg reply and in QC which aggregates all VoteMsg replays
type VoteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id or hash of block
	BlockId []byte `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// Consensus protocol monotonically increasing round number
	RootRound uint64 `protobuf:"varint,2,opt,name=root_round,json=rootRound,proto3" json:"root_round,omitempty"`
	// Epoch number corresponds to the set of validators that are active for this block. (not used)
	Epoch uint64 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// timestamp
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// parent block/proposal id
	ParentBlockId []byte `protobuf:"bytes,5,opt,name=parent_block_id,json=parentBlockId,proto3" json:"parent_block_id,omitempty"`
	// parent block round number
	ParentRound uint64 `protobuf:"varint,6,opt,name=parent_round,json=parentRound,proto3" json:"parent_round,omitempty"`
	// speculative execution state h(root hash || round number)
	ExecStateId []byte `protobuf:"bytes,7,opt,name=exec_state_id,json=execStateId,proto3" json:"exec_state_id,omitempty"`
}

func (x *VoteInfo) Reset() {
	*x = VoteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteInfo) ProtoMessage() {}

func (x *VoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteInfo.ProtoReflect.Descriptor instead.
func (*VoteInfo) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{2}
}

func (x *VoteInfo) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *VoteInfo) GetRootRound() uint64 {
	if x != nil {
		return x.RootRound
	}
	return 0
}

func (x *VoteInfo) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *VoteInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *VoteInfo) GetParentBlockId() []byte {
	if x != nil {
		return x.ParentBlockId
	}
	return nil
}

func (x *VoteInfo) GetParentRound() uint64 {
	if x != nil {
		return x.ParentRound
	}
	return 0
}

func (x *VoteInfo) GetExecStateId() []byte {
	if x != nil {
		return x.ExecStateId
	}
	return nil
}

type LedgerCommitInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hash of VoteInfo
	VoteInfoHash []byte `protobuf:"bytes,1,opt,name=vote_info_hash,json=voteInfoHash,proto3" json:"vote_info_hash,omitempty"`
	// State to be committed
	CommitStateId []byte `protobuf:"bytes,2,opt,name=commit_state_id,json=commitStateId,proto3" json:"commit_state_id,omitempty"`
}

func (x *LedgerCommitInfo) Reset() {
	*x = LedgerCommitInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedgerCommitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCommitInfo) ProtoMessage() {}

func (x *LedgerCommitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCommitInfo.ProtoReflect.Descriptor instead.
func (*LedgerCommitInfo) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{3}
}

func (x *LedgerCommitInfo) GetVoteInfoHash() []byte {
	if x != nil {
		return x.VoteInfoHash
	}
	return nil
}

func (x *LedgerCommitInfo) GetCommitStateId() []byte {
	if x != nil {
		return x.CommitStateId
	}
	return nil
}

type QuorumCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Consensus data
	VoteInfo *VoteInfo `protobuf:"bytes,1,opt,name=vote_info,json=voteInfo,proto3" json:"vote_info,omitempty"`
	// Commit info
	LedgerCommitInfo *LedgerCommitInfo `protobuf:"bytes,2,opt,name=ledger_commit_info,json=ledgerCommitInfo,proto3" json:"ledger_commit_info,omitempty"`
	// Node identifier to signature map (NB! aggregated signature schema in spec)
	Signatures map[string][]byte `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{4}
}

func (x *QuorumCert) GetVoteInfo() *VoteInfo {
	if x != nil {
		return x.VoteInfo
	}
	return nil
}

func (x *QuorumCert) GetLedgerCommitInfo() *LedgerCommitInfo {
	if x != nil {
		return x.LedgerCommitInfo
	}
	return nil
}

func (x *QuorumCert) GetSignatures() map[string][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type BlockData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id hash of block, excluding the id
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// NodeIdentifier of the proposer
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// Root round number
	Round uint64 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	// Epoch to establish valid configuration
	Epoch uint64 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// timestamp
	Timestamp uint64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Payload that will trigger changes to the state
	Payload *Payload `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// quorum certificate for ancestor
	// before payload can be applied check that local state matches state in qc
	// qc.vote_info.proposed.state_hash == h(UC[])
	Qc *QuorumCert `protobuf:"bytes,7,opt,name=qc,proto3" json:"qc,omitempty"`
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{5}
}

func (x *BlockData) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BlockData) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BlockData) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BlockData) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BlockData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockData) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BlockData) GetQc() *QuorumCert {
	if x != nil {
		return x.Qc
	}
	return nil
}

type Timeout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Epoch to establish valid configuration
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Root round number
	Round uint64 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	// Highest quorum certificate of the validator
	Hqc *QuorumCert `protobuf:"bytes,3,opt,name=hqc,proto3" json:"hqc,omitempty"`
}

func (x *Timeout) Reset() {
	*x = Timeout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeout) ProtoMessage() {}

func (x *Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeout.ProtoReflect.Descriptor instead.
func (*Timeout) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{6}
}

func (x *Timeout) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Timeout) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Timeout) GetHqc() *QuorumCert {
	if x != nil {
		return x.Hqc
	}
	return nil
}

type TimeoutWithSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout   *Timeout `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Signature []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TimeoutWithSignature) Reset() {
	*x = TimeoutWithSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutWithSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutWithSignature) ProtoMessage() {}

func (x *TimeoutWithSignature) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutWithSignature.ProtoReflect.Descriptor instead.
func (*TimeoutWithSignature) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{7}
}

func (x *TimeoutWithSignature) GetTimeout() *Timeout {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TimeoutWithSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TimeoutVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// round from timeout.hqc.consensus.round
	HqcRound  uint64 `protobuf:"varint,1,opt,name=hqc_round,json=hqcRound,proto3" json:"hqc_round,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TimeoutVote) Reset() {
	*x = TimeoutVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutVote) ProtoMessage() {}

func (x *TimeoutVote) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutVote.ProtoReflect.Descriptor instead.
func (*TimeoutVote) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{8}
}

func (x *TimeoutVote) GetHqcRound() uint64 {
	if x != nil {
		return x.HqcRound
	}
	return 0
}

func (x *TimeoutVote) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TimeoutCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Round and epoch of the timeout event
	Timeout *Timeout `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// 2f+1 signatures from nodes confirming TC
	Signatures map[string]*TimeoutVote `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TimeoutCert) Reset() {
	*x = TimeoutCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutCert) ProtoMessage() {}

func (x *TimeoutCert) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutCert.ProtoReflect.Descriptor instead.
func (*TimeoutCert) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{9}
}

func (x *TimeoutCert) GetTimeout() *Timeout {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TimeoutCert) GetSignatures() map[string]*TimeoutVote {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type IRChangeReqMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique block certification requests with quorum present or quorum not possible.
	Request *CertificationReqWithProof `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// state hash for synchronization
	ExecStateId []byte `protobuf:"bytes,2,opt,name=exec_state_id,json=execStateId,proto3" json:"exec_state_id,omitempty"`
	// Author who issued the IR change request
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// Signed message to authenticate sender
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *IRChangeReqMsg) Reset() {
	*x = IRChangeReqMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IRChangeReqMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IRChangeReqMsg) ProtoMessage() {}

func (x *IRChangeReqMsg) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IRChangeReqMsg.ProtoReflect.Descriptor instead.
func (*IRChangeReqMsg) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{10}
}

func (x *IRChangeReqMsg) GetRequest() *CertificationReqWithProof {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *IRChangeReqMsg) GetExecStateId() []byte {
	if x != nil {
		return x.ExecStateId
	}
	return nil
}

func (x *IRChangeReqMsg) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *IRChangeReqMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ProposalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Proposed change
	Block *BlockData `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	// highest QC that serves as commit QC, to synchronise on committed state/block
	HighCommitQc *QuorumCert `protobuf:"bytes,2,opt,name=high_commit_qc,json=highCommitQc,proto3" json:"high_commit_qc,omitempty"`
	// Last timeout certificate for block.round - 1 if block.qc.round != block.round - 1
	LastRoundTc *TimeoutCert `protobuf:"bytes,3,opt,name=last_round_tc,json=lastRoundTc,proto3,oneof" json:"last_round_tc,omitempty"`
	// Signature, sign(block_id)
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
}

func (x *ProposalMsg) Reset() {
	*x = ProposalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalMsg) ProtoMessage() {}

func (x *ProposalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalMsg.ProtoReflect.Descriptor instead.
func (*ProposalMsg) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{11}
}

func (x *ProposalMsg) GetBlock() *BlockData {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ProposalMsg) GetHighCommitQc() *QuorumCert {
	if x != nil {
		return x.HighCommitQc
	}
	return nil
}

func (x *ProposalMsg) GetLastRoundTc() *TimeoutCert {
	if x != nil {
		return x.LastRoundTc
	}
	return nil
}

func (x *ProposalMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Message for both timeout and proposal vote
type VoteMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Proposed block hash and resulting state hash
	VoteInfo *VoteInfo `protobuf:"bytes,1,opt,name=vote_info,json=voteInfo,proto3" json:"vote_info,omitempty"`
	// Commit info
	LedgerCommitInfo *LedgerCommitInfo `protobuf:"bytes,2,opt,name=ledger_commit_info,json=ledgerCommitInfo,proto3" json:"ledger_commit_info,omitempty"`
	// Sync highest QC that serves as commit QC
	HighCommitQc *QuorumCert `protobuf:"bytes,3,opt,name=high_commit_qc,json=highCommitQc,proto3" json:"high_commit_qc,omitempty"`
	// Voter node identifier
	Author string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	// Vote signature on hash of consensus info
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// When local timeout expires node may issue a timeout vote (also after voted for proposal).
	// Timeout quorum is aggregated into a TimeoutCert (TC).
	TimeoutSignature *TimeoutWithSignature `protobuf:"bytes,6,opt,name=timeout_signature,json=timeoutSignature,proto3,oneof" json:"timeout_signature,omitempty"`
}

func (x *VoteMsg) Reset() {
	*x = VoteMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteMsg) ProtoMessage() {}

func (x *VoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteMsg.ProtoReflect.Descriptor instead.
func (*VoteMsg) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{12}
}

func (x *VoteMsg) GetVoteInfo() *VoteInfo {
	if x != nil {
		return x.VoteInfo
	}
	return nil
}

func (x *VoteMsg) GetLedgerCommitInfo() *LedgerCommitInfo {
	if x != nil {
		return x.LedgerCommitInfo
	}
	return nil
}

func (x *VoteMsg) GetHighCommitQc() *QuorumCert {
	if x != nil {
		return x.HighCommitQc
	}
	return nil
}

func (x *VoteMsg) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *VoteMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VoteMsg) GetTimeoutSignature() *TimeoutWithSignature {
	if x != nil {
		return x.TimeoutSignature
	}
	return nil
}

type TimeoutMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout   *Timeout `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Signature []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TimeoutMsg) Reset() {
	*x = TimeoutMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutMsg) ProtoMessage() {}

func (x *TimeoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutMsg.ProtoReflect.Descriptor instead.
func (*TimeoutMsg) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{13}
}

func (x *TimeoutMsg) GetTimeout() *Timeout {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TimeoutMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Recover state
type StateRequestMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round uint64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *StateRequestMsg) Reset() {
	*x = StateRequestMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateRequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequestMsg) ProtoMessage() {}

func (x *StateRequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequestMsg.ProtoReflect.Descriptor instead.
func (*StateRequestMsg) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{14}
}

func (x *StateRequestMsg) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type StateReplyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status StateReplyMsg_Status               `protobuf:"varint,1,opt,name=status,proto3,enum=StateReplyMsg_Status" json:"status,omitempty"`
	Uc     []*certificates.UnicityCertificate `protobuf:"bytes,2,rep,name=uc,proto3" json:"uc,omitempty"`
	Qc     []*QuorumCert                      `protobuf:"bytes,3,rep,name=qc,proto3" json:"qc,omitempty"`
}

func (x *StateReplyMsg) Reset() {
	*x = StateReplyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomic_broadcast_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReplyMsg) ProtoMessage() {}

func (x *StateReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_atomic_broadcast_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReplyMsg.ProtoReflect.Descriptor instead.
func (*StateReplyMsg) Descriptor() ([]byte, []int) {
	return file_atomic_broadcast_proto_rawDescGZIP(), []int{15}
}

func (x *StateReplyMsg) GetStatus() StateReplyMsg_Status {
	if x != nil {
		return x.Status
	}
	return StateReplyMsg_OK
}

func (x *StateReplyMsg) GetUc() []*certificates.UnicityCertificate {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *StateReplyMsg) GetQc() []*QuorumCert {
	if x != nil {
		return x.Qc
	}
	return nil
}

var File_atomic_broadcast_proto protoreflect.FileDescriptor

var file_atomic_broadcast_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8c, 0x02, 0x0a, 0x19, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12,
	0x2b, 0x0a, 0x11, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0a,
	0x63, 0x65, 0x72, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x26, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x43, 0x45, 0x52,
	0x54, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x52, 0x0a, 0x63, 0x65, 0x72, 0x74, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x42, 0x0a, 0x0b,
	0x43, 0x45, 0x52, 0x54, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x12, 0x0a, 0x0a, 0x06, 0x51,
	0x55, 0x4f, 0x52, 0x55, 0x4d, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x51, 0x55, 0x4f, 0x52, 0x55,
	0x4d, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x53, 0x49, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x32, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x02,
	0x22, 0x41, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x36, 0x0a, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x22, 0xe7, 0x01, 0x0a, 0x08, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x6f, 0x6f, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x72, 0x6f, 0x6f, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x26,
	0x0a, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x78, 0x65,
	0x63, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22, 0x60, 0x0a,
	0x10, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x24, 0x0a, 0x0e, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x22,
	0xf1, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x12, 0x26,
	0x0a, 0x09, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x76, 0x6f,
	0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3f, 0x0a, 0x12, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x10, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x51, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0xbe, 0x01, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x02, 0x71, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74,
	0x52, 0x02, 0x71, 0x63, 0x22, 0x54, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x03, 0x68,
	0x71, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75,
	0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x03, 0x68, 0x71, 0x63, 0x22, 0x58, 0x0a, 0x14, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x57, 0x69, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x48, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x56,
	0x6f, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x71, 0x63, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x68, 0x71, 0x63, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xbc,
	0x01, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x65, 0x72, 0x74, 0x12, 0x22,
	0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x43, 0x65, 0x72, 0x74, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x1a, 0x4b, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x56, 0x6f,
	0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa0, 0x01,
	0x0a, 0x0e, 0x49, 0x52, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x4d, 0x73, 0x67,
	0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x65,
	0x78, 0x65, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x22, 0xdc, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4d, 0x73, 0x67,
	0x12, 0x20, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x31, 0x0a, 0x0e, 0x68, 0x69, 0x67, 0x68, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x71, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x51, 0x75, 0x6f,
	0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x0c, 0x68, 0x69, 0x67, 0x68, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x51, 0x63, 0x12, 0x35, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x5f, 0x74, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x65, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x54, 0x63, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x01, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x74,
	0x63, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0xba, 0x02, 0x0a, 0x07, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x26, 0x0a, 0x09, 0x76,
	0x6f, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x76, 0x6f, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x3f, 0x0a, 0x12, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x10, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x0e, 0x68, 0x69, 0x67, 0x68, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x5f, 0x71, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x51,
	0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x0c, 0x68, 0x69, 0x67, 0x68, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x51, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x47, 0x0a,
	0x11, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x57, 0x69, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48,
	0x00, 0x52, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x4e, 0x0a, 0x0a,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x27, 0x0a, 0x0f,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x02, 0x75, 0x63, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x55, 0x6e, 0x69, 0x63, 0x69, 0x74, 0x79, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x02, 0x75, 0x63, 0x12, 0x1b, 0x0a, 0x02, 0x71,
	0x63, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d,
	0x43, 0x65, 0x72, 0x74, 0x52, 0x02, 0x71, 0x63, 0x22, 0x23, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x01, 0x42, 0x60, 0x5a,
	0x5e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x6f, 0x72, 0x67, 0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x62,
	0x69, 0x6c, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x74,
	0x6f, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x3b, 0x61,
	0x74, 0x6f, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_atomic_broadcast_proto_rawDescOnce sync.Once
	file_atomic_broadcast_proto_rawDescData = file_atomic_broadcast_proto_rawDesc
)

func file_atomic_broadcast_proto_rawDescGZIP() []byte {
	file_atomic_broadcast_proto_rawDescOnce.Do(func() {
		file_atomic_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(file_atomic_broadcast_proto_rawDescData)
	})
	return file_atomic_broadcast_proto_rawDescData
}

var file_atomic_broadcast_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_atomic_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_atomic_broadcast_proto_goTypes = []interface{}{
	(CertificationReqWithProof_CERT_REASON)(0), // 0: CertificationReqWithProof.CERT_REASON
	(StateReplyMsg_Status)(0),                  // 1: StateReplyMsg.Status
	(*CertificationReqWithProof)(nil),          // 2: CertificationReqWithProof
	(*Payload)(nil),                            // 3: Payload
	(*VoteInfo)(nil),                           // 4: VoteInfo
	(*LedgerCommitInfo)(nil),                   // 5: LedgerCommitInfo
	(*QuorumCert)(nil),                         // 6: QuorumCert
	(*BlockData)(nil),                          // 7: BlockData
	(*Timeout)(nil),                            // 8: Timeout
	(*TimeoutWithSignature)(nil),               // 9: TimeoutWithSignature
	(*TimeoutVote)(nil),                        // 10: TimeoutVote
	(*TimeoutCert)(nil),                        // 11: TimeoutCert
	(*IRChangeReqMsg)(nil),                     // 12: IRChangeReqMsg
	(*ProposalMsg)(nil),                        // 13: ProposalMsg
	(*VoteMsg)(nil),                            // 14: VoteMsg
	(*TimeoutMsg)(nil),                         // 15: TimeoutMsg
	(*StateRequestMsg)(nil),                    // 16: StateRequestMsg
	(*StateReplyMsg)(nil),                      // 17: StateReplyMsg
	nil,                                        // 18: QuorumCert.SignaturesEntry
	nil,                                        // 19: TimeoutCert.SignaturesEntry
	(*certification.BlockCertificationRequest)(nil), // 20: BlockCertificationRequest
	(*certificates.UnicityCertificate)(nil),         // 21: UnicityCertificate
}
var file_atomic_broadcast_proto_depIdxs = []int32{
	0,  // 0: CertificationReqWithProof.certReason:type_name -> CertificationReqWithProof.CERT_REASON
	20, // 1: CertificationReqWithProof.requests:type_name -> BlockCertificationRequest
	2,  // 2: Payload.requests:type_name -> CertificationReqWithProof
	4,  // 3: QuorumCert.vote_info:type_name -> VoteInfo
	5,  // 4: QuorumCert.ledger_commit_info:type_name -> LedgerCommitInfo
	18, // 5: QuorumCert.signatures:type_name -> QuorumCert.SignaturesEntry
	3,  // 6: BlockData.payload:type_name -> Payload
	6,  // 7: BlockData.qc:type_name -> QuorumCert
	6,  // 8: Timeout.hqc:type_name -> QuorumCert
	8,  // 9: TimeoutWithSignature.timeout:type_name -> Timeout
	8,  // 10: TimeoutCert.timeout:type_name -> Timeout
	19, // 11: TimeoutCert.signatures:type_name -> TimeoutCert.SignaturesEntry
	2,  // 12: IRChangeReqMsg.request:type_name -> CertificationReqWithProof
	7,  // 13: ProposalMsg.block:type_name -> BlockData
	6,  // 14: ProposalMsg.high_commit_qc:type_name -> QuorumCert
	11, // 15: ProposalMsg.last_round_tc:type_name -> TimeoutCert
	4,  // 16: VoteMsg.vote_info:type_name -> VoteInfo
	5,  // 17: VoteMsg.ledger_commit_info:type_name -> LedgerCommitInfo
	6,  // 18: VoteMsg.high_commit_qc:type_name -> QuorumCert
	9,  // 19: VoteMsg.timeout_signature:type_name -> TimeoutWithSignature
	8,  // 20: TimeoutMsg.timeout:type_name -> Timeout
	1,  // 21: StateReplyMsg.status:type_name -> StateReplyMsg.Status
	21, // 22: StateReplyMsg.uc:type_name -> UnicityCertificate
	6,  // 23: StateReplyMsg.qc:type_name -> QuorumCert
	10, // 24: TimeoutCert.SignaturesEntry.value:type_name -> TimeoutVote
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_atomic_broadcast_proto_init() }
func file_atomic_broadcast_proto_init() {
	if File_atomic_broadcast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_atomic_broadcast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertificationReqWithProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedgerCommitInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuorumCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timeout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutWithSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IRChangeReqMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateRequestMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomic_broadcast_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateReplyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_atomic_broadcast_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_atomic_broadcast_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_atomic_broadcast_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atomic_broadcast_proto_goTypes,
		DependencyIndexes: file_atomic_broadcast_proto_depIdxs,
		EnumInfos:         file_atomic_broadcast_proto_enumTypes,
		MessageInfos:      file_atomic_broadcast_proto_msgTypes,
	}.Build()
	File_atomic_broadcast_proto = out.File
	file_atomic_broadcast_proto_rawDesc = nil
	file_atomic_broadcast_proto_goTypes = nil
	file_atomic_broadcast_proto_depIdxs = nil
}
