basePath: /api/v1
definitions:
  backend.BalanceResponse:
    properties:
      balance:
        example: "0"
        type: string
    type: object
  backend.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  backend.ListBillVM:
    properties:
      id:
        example: AAAAAAgwv3UA1HfGO4qc1T3I3EOvqxfcrhMjJpr9Tn4=
        format: base64
        type: string
      isDcBill:
        example: false
        type: boolean
      txHash:
        example: Q4ShCITC0ODXPR+j1Zl/teYcoU3/mAPy0x8uSsvQFM8=
        format: base64
        type: string
      value:
        example: "1000"
        type: string
    type: object
  backend.ListBillsResponse:
    properties:
      bills:
        items:
          $ref: '#/definitions/backend.ListBillVM'
        type: array
      total:
        example: 1
        type: integer
    type: object
  backend.RoundNumberResponse:
    properties:
      roundNumber:
        example: "0"
        type: string
    type: object
  types.ClientMetadata:
    properties:
      feeCreditRecordID:
        items:
          type: integer
        type: array
      maxTransactionFee:
        type: integer
      timeout:
        type: integer
    type: object
  types.GenericChainItem:
    properties:
      hash:
        items:
          type: integer
        type: array
      left:
        type: boolean
    type: object
  types.InputRecord:
    properties:
      block_hash:
        description: hash of the block
        items:
          type: integer
        type: array
      hash:
        description: state hash to be certified
        items:
          type: integer
        type: array
      previous_hash:
        description: previously certified state hash
        items:
          type: integer
        type: array
      round_number:
        description: transaction system's round number
        type: integer
      sum_of_earned_fees:
        description: sum of the actual fees over all transaction records in the block
        type: integer
      summary_value:
        description: summary value to certified
        items:
          type: integer
        type: array
    type: object
  types.Payload:
    properties:
      attributes:
        items:
          type: integer
        type: array
      clientMetadata:
        $ref: '#/definitions/types.ClientMetadata'
      systemID:
        items:
          type: integer
        type: array
      type:
        type: string
      unitID:
        items:
          type: integer
        type: array
    type: object
  types.ServerMetadata:
    properties:
      actualFee:
        type: integer
      targetUnits:
        items:
          items:
            type: integer
          type: array
        type: array
    type: object
  types.TransactionOrder:
    properties:
      feeProof:
        items:
          type: integer
        type: array
      ownerProof:
        items:
          type: integer
        type: array
      payload:
        $ref: '#/definitions/types.Payload'
    type: object
  types.TransactionRecord:
    properties:
      serverMetadata:
        $ref: '#/definitions/types.ServerMetadata'
      transactionOrder:
        $ref: '#/definitions/types.TransactionOrder'
    type: object
  types.TxProof:
    properties:
      blockHeaderHash:
        items:
          type: integer
        type: array
      chain:
        items:
          $ref: '#/definitions/types.GenericChainItem'
        type: array
      unicityCertificate:
        $ref: '#/definitions/types.UnicityCertificate'
    type: object
  types.UnicityCertificate:
    properties:
      input_record:
        $ref: '#/definitions/types.InputRecord'
      unicity_seal:
        $ref: '#/definitions/types.UnicitySeal'
      unicity_tree_certificate:
        $ref: '#/definitions/types.UnicityTreeCertificate'
    type: object
  types.UnicitySeal:
    properties:
      hash:
        items:
          type: integer
        type: array
      previous_hash:
        items:
          type: integer
        type: array
      root_chain_round_number:
        type: integer
      signatures:
        additionalProperties:
          items:
            type: integer
          type: array
        type: object
      timestamp:
        type: integer
    type: object
  types.UnicityTreeCertificate:
    properties:
      sibling_hashes:
        items:
          items:
            type: integer
          type: array
        type: array
      system_description_hash:
        items:
          type: integer
        type: array
      system_identifier:
        items:
          type: integer
        type: array
    type: object
  wallet.Bill:
    properties:
      fc_block_number:
        description: block number when fee credit bill balance was last updated
        example: "0"
        type: string
      id:
        items:
          type: integer
        type: array
      is_dc_bill:
        type: boolean
      tx_hash:
        items:
          type: integer
        type: array
      tx_proof:
        $ref: '#/definitions/wallet.Proof'
      value:
        example: "0"
        type: string
    type: object
  wallet.Bills:
    properties:
      bills:
        items:
          $ref: '#/definitions/wallet.Bill'
        type: array
    type: object
  wallet.Proof:
    properties:
      txProof:
        $ref: '#/definitions/types.TxProof'
      txRecord:
        $ref: '#/definitions/types.TransactionRecord'
    type: object
info:
  contact: {}
  description: This service processes blocks from the Money partition and indexes
    ownership of bills.
  title: Money Partition Indexing Backend API
  version: "1.0"
paths:
  /balance:
    get:
      operationId: "2"
      parameters:
      - description: Public key prefixed with 0x
        in: query
        name: pubkey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend.BalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/backend.ErrorResponse'
        "500":
          description: Internal Server Error
      summary: Get balance
  /fee-credit-bills:
    get:
      operationId: "5"
      parameters:
      - description: ID of the bill (hex)
        in: path
        name: billId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.Bill'
      summary: Get Fee Credit Bill
  /list-bills:
    get:
      operationId: "1"
      parameters:
      - description: Public key prefixed with 0x
        example: "0x000000000000000000000000000000000000000000000000000000000000000123"
        in: query
        name: pubkey
        required: true
        type: string
      - default: 100
        description: limits how many bills are returned in response
        in: query
        name: limit
        type: integer
      - default: 0
        description: response will include bills starting after offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend.ListBillsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/backend.ErrorResponse'
        "500":
          description: Internal Server Error
      summary: List bills
  /proof:
    get:
      operationId: "3"
      parameters:
      - description: ID of the bill (hex)
        in: query
        name: bill_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.Bills'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/backend.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/backend.ErrorResponse'
        "500":
          description: Internal Server Error
      summary: Get proof
  /round-number:
    get:
      operationId: "4"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend.RoundNumberResponse'
      summary: Money partition's latest block number
  /transactions:
    post:
      consumes:
      - application/cbor
      operationId: "6"
      parameters:
      - description: Sender public key prefixed with 0x
        in: path
        name: pubkey
        required: true
        type: string
      - description: CBOR encoded array of TransactionOrders
        in: body
        name: transactions
        required: true
      responses:
        "202":
          description: Accepted
      summary: Forward transactions to partition node(s)
swagger: "2.0"
