// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: alphabill.proto

package alphabill

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlphabillServiceClient is the abclient API for AlphabillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlphabillServiceClient interface {
	ProcessTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	GetRoundNumber(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRoundNumberResponse, error)
}

type alphabillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlphabillServiceClient(cc grpc.ClientConnInterface) AlphabillServiceClient {
	return &alphabillServiceClient{cc}
}

func (c *alphabillServiceClient) ProcessTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/abrpc.AlphabillService/ProcessTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alphabillServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/abrpc.AlphabillService/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alphabillServiceClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, "/abrpc.AlphabillService/GetBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alphabillServiceClient) GetRoundNumber(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRoundNumberResponse, error) {
	out := new(GetRoundNumberResponse)
	err := c.cc.Invoke(ctx, "/abrpc.AlphabillService/GetRoundNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlphabillServiceServer is the server API for AlphabillService service.
// All implementations must embed UnimplementedAlphabillServiceServer
// for forward compatibility
type AlphabillServiceServer interface {
	ProcessTransaction(context.Context, *Transaction) (*emptypb.Empty, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	GetRoundNumber(context.Context, *emptypb.Empty) (*GetRoundNumberResponse, error)
	mustEmbedUnimplementedAlphabillServiceServer()
}

// UnimplementedAlphabillServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlphabillServiceServer struct {
}

func (UnimplementedAlphabillServiceServer) ProcessTransaction(context.Context, *Transaction) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTransaction not implemented")
}
func (UnimplementedAlphabillServiceServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedAlphabillServiceServer) GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedAlphabillServiceServer) GetRoundNumber(context.Context, *emptypb.Empty) (*GetRoundNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoundNumber not implemented")
}
func (UnimplementedAlphabillServiceServer) mustEmbedUnimplementedAlphabillServiceServer() {}

// UnsafeAlphabillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlphabillServiceServer will
// result in compilation errors.
type UnsafeAlphabillServiceServer interface {
	mustEmbedUnimplementedAlphabillServiceServer()
}

func RegisterAlphabillServiceServer(s grpc.ServiceRegistrar, srv AlphabillServiceServer) {
	s.RegisterService(&AlphabillService_ServiceDesc, srv)
}

func _AlphabillService_ProcessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlphabillServiceServer).ProcessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abrpc.AlphabillService/ProcessTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlphabillServiceServer).ProcessTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlphabillService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlphabillServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abrpc.AlphabillService/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlphabillServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlphabillService_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlphabillServiceServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abrpc.AlphabillService/GetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlphabillServiceServer).GetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlphabillService_GetRoundNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlphabillServiceServer).GetRoundNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abrpc.AlphabillService/GetRoundNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlphabillServiceServer).GetRoundNumber(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AlphabillService_ServiceDesc is the grpc.ServiceDesc for AlphabillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlphabillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abrpc.AlphabillService",
	HandlerType: (*AlphabillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTransaction",
			Handler:    _AlphabillService_ProcessTransaction_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _AlphabillService_GetBlock_Handler,
		},
		{
			MethodName: "GetBlocks",
			Handler:    _AlphabillService_GetBlocks_Handler,
		},
		{
			MethodName: "GetRoundNumber",
			Handler:    _AlphabillService_GetRoundNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alphabill.proto",
}
