# File name to log to. If not set, logs to stdout.
outputPath:
# Set to true to log in console optimized way. If false, uses JSON format.
consoleFormat: false
# Controls if the log caller file name and row number is added to log.
showCaller: true
# The time zone for log messages.
timeLocation: UTC
# Controls if goroutine ID is added to log.
showGoroutineID: true
# Controls if Node ID is added to log.
showNodeID: true
# The default log level for all loggers
# Possible levels: NONE; ERROR; WARNING; INFO; DEBUG; TRACE
defaultLevel: DEBUG
# Override the logger level for each package. Use _ for separating directories and other special characters.
# E.g. internal/txsystem/state becomes internal_txsystem_state.
packageLevels:
  internal_txbuffer: WARNING
