// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "gitdc.ee.guardtime.com/alphabill/alphabill/internal/domain"
	mock "github.com/stretchr/testify/mock"

	transaction "gitdc.ee.guardtime.com/alphabill/alphabill/internal/rpc/transaction"
)

// TransactionOrderConverter is an autogenerated mock type for the TransactionOrderConverter type
type TransactionOrderConverter struct {
	mock.Mock
}

// ConvertPbToDomain provides a mock function with given fields: pbTxOrder
func (_m *TransactionOrderConverter) ConvertPbToDomain(pbTxOrder *transaction.TransactionOrder) (*domain.TransactionOrder, error) {
	ret := _m.Called(pbTxOrder)

	var r0 *domain.TransactionOrder
	if rf, ok := ret.Get(0).(func(*transaction.TransactionOrder) *domain.TransactionOrder); ok {
		r0 = rf(pbTxOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransactionOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*transaction.TransactionOrder) error); ok {
		r1 = rf(pbTxOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
