// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.9
// source: bills.proto

package money

import (
	block "github.com/alphabill-org/alphabill/internal/block"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// bills with tx proofs
type Bills struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bills []*Bill `protobuf:"bytes,1,rep,name=bills,proto3" json:"bills,omitempty"`
}

func (x *Bills) Reset() {
	*x = Bills{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bills_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bills) ProtoMessage() {}

func (x *Bills) ProtoReflect() protoreflect.Message {
	mi := &file_bills_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bills.ProtoReflect.Descriptor instead.
func (*Bills) Descriptor() ([]byte, []int) {
	return file_bills_proto_rawDescGZIP(), []int{0}
}

func (x *Bills) GetBills() []*Bill {
	if x != nil {
		return x.Bills
	}
	return nil
}

// bill with tx proof
type Bill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value    uint64         `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	TxHash   []byte         `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	IsDcBill bool           `protobuf:"varint,4,opt,name=is_dc_bill,json=isDcBill,proto3" json:"is_dc_bill,omitempty"`
	TxProof  *block.TxProof `protobuf:"bytes,5,opt,name=tx_proof,json=txProof,proto3" json:"tx_proof,omitempty"`
}

func (x *Bill) Reset() {
	*x = Bill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bills_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_bills_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_bills_proto_rawDescGZIP(), []int{1}
}

func (x *Bill) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Bill) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Bill) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *Bill) GetIsDcBill() bool {
	if x != nil {
		return x.IsDcBill
	}
	return false
}

func (x *Bill) GetTxProof() *block.TxProof {
	if x != nil {
		return x.TxProof
	}
	return nil
}

var File_bills_proto protoreflect.FileDescriptor

var file_bills_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x69, 0x6c, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x24, 0x0a, 0x05, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x62, 0x69, 0x6c,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x05, 0x62, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c,
	0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x63, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x44, 0x63, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x23, 0x0a, 0x08,
	0x74, 0x78, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x07, 0x74, 0x78, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x6f, 0x72, 0x67, 0x2f, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x62, 0x69, 0x6c, 0x6c, 0x2f, 0x74, 0x78, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x3b, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bills_proto_rawDescOnce sync.Once
	file_bills_proto_rawDescData = file_bills_proto_rawDesc
)

func file_bills_proto_rawDescGZIP() []byte {
	file_bills_proto_rawDescOnce.Do(func() {
		file_bills_proto_rawDescData = protoimpl.X.CompressGZIP(file_bills_proto_rawDescData)
	})
	return file_bills_proto_rawDescData
}

var file_bills_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bills_proto_goTypes = []interface{}{
	(*Bills)(nil),         // 0: Bills
	(*Bill)(nil),          // 1: Bill
	(*block.TxProof)(nil), // 2: TxProof
}
var file_bills_proto_depIdxs = []int32{
	1, // 0: Bills.bills:type_name -> Bill
	2, // 1: Bill.tx_proof:type_name -> TxProof
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bills_proto_init() }
func file_bills_proto_init() {
	if File_bills_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bills_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bills); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bills_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bills_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bills_proto_goTypes,
		DependencyIndexes: file_bills_proto_depIdxs,
		MessageInfos:      file_bills_proto_msgTypes,
	}.Build()
	File_bills_proto = out.File
	file_bills_proto_rawDesc = nil
	file_bills_proto_goTypes = nil
	file_bills_proto_depIdxs = nil
}
