// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: money_tx.proto

package money

import (
	block "github.com/alphabill-org/alphabill/internal/block"
	txsystem "github.com/alphabill-org/alphabill/internal/txsystem"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewBearer   []byte `protobuf:"bytes,1,opt,name=new_bearer,json=newBearer,proto3" json:"new_bearer,omitempty"`
	TargetValue uint64 `protobuf:"varint,2,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	Backlink    []byte `protobuf:"bytes,3,opt,name=backlink,proto3" json:"backlink,omitempty"`
}

func (x *TransferOrder) Reset() {
	*x = TransferOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_money_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOrder) ProtoMessage() {}

func (x *TransferOrder) ProtoReflect() protoreflect.Message {
	mi := &file_money_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOrder.ProtoReflect.Descriptor instead.
func (*TransferOrder) Descriptor() ([]byte, []int) {
	return file_money_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TransferOrder) GetNewBearer() []byte {
	if x != nil {
		return x.NewBearer
	}
	return nil
}

func (x *TransferOrder) GetTargetValue() uint64 {
	if x != nil {
		return x.TargetValue
	}
	return 0
}

func (x *TransferOrder) GetBacklink() []byte {
	if x != nil {
		return x.Backlink
	}
	return nil
}

type TransferDCOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce        []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TargetBearer []byte `protobuf:"bytes,2,opt,name=target_bearer,json=targetBearer,proto3" json:"target_bearer,omitempty"`
	TargetValue  uint64 `protobuf:"varint,3,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	Backlink     []byte `protobuf:"bytes,4,opt,name=backlink,proto3" json:"backlink,omitempty"`
}

func (x *TransferDCOrder) Reset() {
	*x = TransferDCOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_money_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferDCOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferDCOrder) ProtoMessage() {}

func (x *TransferDCOrder) ProtoReflect() protoreflect.Message {
	mi := &file_money_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferDCOrder.ProtoReflect.Descriptor instead.
func (*TransferDCOrder) Descriptor() ([]byte, []int) {
	return file_money_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TransferDCOrder) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *TransferDCOrder) GetTargetBearer() []byte {
	if x != nil {
		return x.TargetBearer
	}
	return nil
}

func (x *TransferDCOrder) GetTargetValue() uint64 {
	if x != nil {
		return x.TargetValue
	}
	return 0
}

func (x *TransferDCOrder) GetBacklink() []byte {
	if x != nil {
		return x.Backlink
	}
	return nil
}

type SplitOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount         uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	TargetBearer   []byte `protobuf:"bytes,2,opt,name=target_bearer,json=targetBearer,proto3" json:"target_bearer,omitempty"`
	RemainingValue uint64 `protobuf:"varint,3,opt,name=remaining_value,json=remainingValue,proto3" json:"remaining_value,omitempty"`
	Backlink       []byte `protobuf:"bytes,4,opt,name=backlink,proto3" json:"backlink,omitempty"`
}

func (x *SplitOrder) Reset() {
	*x = SplitOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_money_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitOrder) ProtoMessage() {}

func (x *SplitOrder) ProtoReflect() protoreflect.Message {
	mi := &file_money_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitOrder.ProtoReflect.Descriptor instead.
func (*SplitOrder) Descriptor() ([]byte, []int) {
	return file_money_tx_proto_rawDescGZIP(), []int{2}
}

func (x *SplitOrder) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SplitOrder) GetTargetBearer() []byte {
	if x != nil {
		return x.TargetBearer
	}
	return nil
}

func (x *SplitOrder) GetRemainingValue() uint64 {
	if x != nil {
		return x.RemainingValue
	}
	return 0
}

func (x *SplitOrder) GetBacklink() []byte {
	if x != nil {
		return x.Backlink
	}
	return nil
}

type SwapOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerCondition  []byte                  `protobuf:"bytes,1,opt,name=owner_condition,json=ownerCondition,proto3" json:"owner_condition,omitempty"`
	BillIdentifiers [][]byte                `protobuf:"bytes,2,rep,name=bill_identifiers,json=billIdentifiers,proto3" json:"bill_identifiers,omitempty"`
	DcTransfers     []*txsystem.Transaction `protobuf:"bytes,3,rep,name=dc_transfers,json=dcTransfers,proto3" json:"dc_transfers,omitempty"`
	Proofs          []*block.BlockProof     `protobuf:"bytes,4,rep,name=proofs,proto3" json:"proofs,omitempty"`
	TargetValue     uint64                  `protobuf:"varint,5,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
}

func (x *SwapOrder) Reset() {
	*x = SwapOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_money_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapOrder) ProtoMessage() {}

func (x *SwapOrder) ProtoReflect() protoreflect.Message {
	mi := &file_money_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapOrder.ProtoReflect.Descriptor instead.
func (*SwapOrder) Descriptor() ([]byte, []int) {
	return file_money_tx_proto_rawDescGZIP(), []int{3}
}

func (x *SwapOrder) GetOwnerCondition() []byte {
	if x != nil {
		return x.OwnerCondition
	}
	return nil
}

func (x *SwapOrder) GetBillIdentifiers() [][]byte {
	if x != nil {
		return x.BillIdentifiers
	}
	return nil
}

func (x *SwapOrder) GetDcTransfers() []*txsystem.Transaction {
	if x != nil {
		return x.DcTransfers
	}
	return nil
}

func (x *SwapOrder) GetProofs() []*block.BlockProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

func (x *SwapOrder) GetTargetValue() uint64 {
	if x != nil {
		return x.TargetValue
	}
	return 0
}

var File_money_tx_proto protoreflect.FileDescriptor

var file_money_tx_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0d, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x6e, 0x65, 0x77, 0x5f, 0x62, 0x65, 0x61, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x6e, 0x65, 0x77, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x44, 0x43, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x62,
	0x65, 0x61, 0x72, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x53, 0x70, 0x6c,
	0x69, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x65, 0x61, 0x72, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x65,
	0x61, 0x72, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0xd8, 0x01, 0x0a, 0x09, 0x53, 0x77,
	0x61, 0x70, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0e, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x10, 0x62, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0f, 0x62, 0x69, 0x6c, 0x6c,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x0c, 0x64,
	0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x64, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x06,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x62, 0x69, 0x6c, 0x6c, 0x2d, 0x6f, 0x72, 0x67,
	0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x62, 0x69, 0x6c, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x78, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x2f, 0x3b, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_money_tx_proto_rawDescOnce sync.Once
	file_money_tx_proto_rawDescData = file_money_tx_proto_rawDesc
)

func file_money_tx_proto_rawDescGZIP() []byte {
	file_money_tx_proto_rawDescOnce.Do(func() {
		file_money_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_money_tx_proto_rawDescData)
	})
	return file_money_tx_proto_rawDescData
}

var file_money_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_money_tx_proto_goTypes = []interface{}{
	(*TransferOrder)(nil),        // 0: rpc.TransferOrder
	(*TransferDCOrder)(nil),      // 1: rpc.TransferDCOrder
	(*SplitOrder)(nil),           // 2: rpc.SplitOrder
	(*SwapOrder)(nil),            // 3: rpc.SwapOrder
	(*txsystem.Transaction)(nil), // 4: Transaction
	(*block.BlockProof)(nil),     // 5: BlockProof
}
var file_money_tx_proto_depIdxs = []int32{
	4, // 0: rpc.SwapOrder.dc_transfers:type_name -> Transaction
	5, // 1: rpc.SwapOrder.proofs:type_name -> BlockProof
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_money_tx_proto_init() }
func file_money_tx_proto_init() {
	if File_money_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_money_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_money_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferDCOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_money_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_money_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwapOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_money_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_money_tx_proto_goTypes,
		DependencyIndexes: file_money_tx_proto_depIdxs,
		MessageInfos:      file_money_tx_proto_msgTypes,
	}.Build()
	File_money_tx_proto = out.File
	file_money_tx_proto_rawDesc = nil
	file_money_tx_proto_goTypes = nil
	file_money_tx_proto_depIdxs = nil
}
