// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: p1.proto

package p1

import (
	certificates "gitdc.ee.guardtime.com/alphabill/alphabill/internal/certificates"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type P1Response_Status int32

const (
	P1Response_OK         P1Response_Status = 0
	P1Response_INVALID    P1Response_Status = 1
	P1Response_DUPLICATE  P1Response_Status = 2
	P1Response_SUPERSEDED P1Response_Status = 3
	P1Response_REPLACED   P1Response_Status = 4
)

// Enum value maps for P1Response_Status.
var (
	P1Response_Status_name = map[int32]string{
		0: "OK",
		1: "INVALID",
		2: "DUPLICATE",
		3: "SUPERSEDED",
		4: "REPLACED",
	}
	P1Response_Status_value = map[string]int32{
		"OK":         0,
		"INVALID":    1,
		"DUPLICATE":  2,
		"SUPERSEDED": 3,
		"REPLACED":   4,
	}
)

func (x P1Response_Status) Enum() *P1Response_Status {
	p := new(P1Response_Status)
	*p = x
	return p
}

func (x P1Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (P1Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_p1_proto_enumTypes[0].Descriptor()
}

func (P1Response_Status) Type() protoreflect.EnumType {
	return &file_p1_proto_enumTypes[0]
}

func (x P1Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use P1Response_Status.Descriptor instead.
func (P1Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_p1_proto_rawDescGZIP(), []int{1, 0}
}

type P1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemIdentifier []byte                    `protobuf:"bytes,1,opt,name=system_identifier,json=systemIdentifier,proto3" json:"system_identifier,omitempty"`
	NodeIdentifier   string                    `protobuf:"bytes,2,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	RootRoundNumber  uint64                    `protobuf:"varint,3,opt,name=root_round_number,json=rootRoundNumber,proto3" json:"root_round_number,omitempty"`
	InputRecord      *certificates.InputRecord `protobuf:"bytes,4,opt,name=input_record,json=inputRecord,proto3" json:"input_record,omitempty"`
	Signature        []byte                    `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *P1Request) Reset() {
	*x = P1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P1Request) ProtoMessage() {}

func (x *P1Request) ProtoReflect() protoreflect.Message {
	mi := &file_p1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P1Request.ProtoReflect.Descriptor instead.
func (*P1Request) Descriptor() ([]byte, []int) {
	return file_p1_proto_rawDescGZIP(), []int{0}
}

func (x *P1Request) GetSystemIdentifier() []byte {
	if x != nil {
		return x.SystemIdentifier
	}
	return nil
}

func (x *P1Request) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

func (x *P1Request) GetRootRoundNumber() uint64 {
	if x != nil {
		return x.RootRoundNumber
	}
	return 0
}

func (x *P1Request) GetInputRecord() *certificates.InputRecord {
	if x != nil {
		return x.InputRecord
	}
	return nil
}

func (x *P1Request) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type P1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// True if request passed initial validation.
	Status P1Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=P1Response_Status" json:"status,omitempty"`
	// Contains error message if ok is false.
	Message *certificates.UnicityCertificate `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *P1Response) Reset() {
	*x = P1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P1Response) ProtoMessage() {}

func (x *P1Response) ProtoReflect() protoreflect.Message {
	mi := &file_p1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P1Response.ProtoReflect.Descriptor instead.
func (*P1Response) Descriptor() ([]byte, []int) {
	return file_p1_proto_rawDescGZIP(), []int{1}
}

func (x *P1Response) GetStatus() P1Response_Status {
	if x != nil {
		return x.Status
	}
	return P1Response_OK
}

func (x *P1Response) GetMessage() *certificates.UnicityCertificate {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_p1_proto protoreflect.FileDescriptor

var file_p1_proto_rawDesc = []byte{
	0x0a, 0x08, 0x70, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc,
	0x01, 0x0a, 0x09, 0x50, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x72,
	0x6f, 0x6f, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2f,
	0x0a, 0x0c, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xb3, 0x01,
	0x0a, 0x0a, 0x50, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x50,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x55, 0x6e, 0x69, 0x63,
	0x69, 0x74, 0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x50, 0x45, 0x52, 0x53, 0x45,
	0x44, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45,
	0x44, 0x10, 0x04, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x64, 0x63, 0x2e, 0x65, 0x65, 0x2e,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x62, 0x69, 0x6c, 0x6c, 0x2f, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x62, 0x69, 0x6c,
	0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x31, 0x3b, 0x70, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_p1_proto_rawDescOnce sync.Once
	file_p1_proto_rawDescData = file_p1_proto_rawDesc
)

func file_p1_proto_rawDescGZIP() []byte {
	file_p1_proto_rawDescOnce.Do(func() {
		file_p1_proto_rawDescData = protoimpl.X.CompressGZIP(file_p1_proto_rawDescData)
	})
	return file_p1_proto_rawDescData
}

var file_p1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_p1_proto_goTypes = []interface{}{
	(P1Response_Status)(0),                  // 0: P1Response.Status
	(*P1Request)(nil),                       // 1: P1Request
	(*P1Response)(nil),                      // 2: P1Response
	(*certificates.InputRecord)(nil),        // 3: InputRecord
	(*certificates.UnicityCertificate)(nil), // 4: UnicityCertificate
}
var file_p1_proto_depIdxs = []int32{
	3, // 0: P1Request.input_record:type_name -> InputRecord
	0, // 1: P1Response.status:type_name -> P1Response.Status
	4, // 2: P1Response.message:type_name -> UnicityCertificate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_p1_proto_init() }
func file_p1_proto_init() {
	if File_p1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p1_proto_goTypes,
		DependencyIndexes: file_p1_proto_depIdxs,
		EnumInfos:         file_p1_proto_enumTypes,
		MessageInfos:      file_p1_proto_msgTypes,
	}.Build()
	File_p1_proto = out.File
	file_p1_proto_rawDesc = nil
	file_p1_proto_goTypes = nil
	file_p1_proto_depIdxs = nil
}
