openapi: 3.1.0
info:
  title: Money Partition Indexing Backend API
  description: |-
    Money partition indexing backend processes blocks from the money
    partition and indexes ownership of the bills. This API provides
    access to the indexed data.
  version: '1.0'
servers:
  - url: /api/v1
  - url: http://localhost:{port}/api/v1
    variables:
      port:
        default: '9654'
paths:
  /round-number:
    get:
      summary: Get the latest round number of the money partition
      description: |-
        Returns the round number of the latest certified round known
        to the partition node which indexing backend is connected
        to. Useful for calculating transaction timeout values.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/schemas/RoundNumberResponse'
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /balance:
    get:
      summary: Get the balance for a public key
      description: |-
        Returns the sum of all bills owned by the given public key.
      parameters:
        - description: Hex encoded public key prefixed with `0x`
          in: query
          name: pubkey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /list-bills:
    get:
      summary: List bills owned by a public key. Supports paging with the offsetKey and limit parameters.
      description: |-
        Returns all bills owned by the given public key.
      parameters:
        - name: pubkey
          description: Hex encoded public key prefixed with `0x`
          in: query
          required: true
          schema:
            type: string
          example: '0x000000000000000000000000000000000000000000000000000000000000000123'
        - name: limit
          description: Maximum number of items in the response
          in: query
          required: false
          schema:
            type: integer
        - name: offsetKey
          description: When doing batched queries, offset key returned by the previous query
          in: query
          required: false
          schema:
            type: string
        - name: includeDcBills
          description: Response will include DC bills
          in: query
          schema:
            type: bool
            default: false
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBillsResponse'
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /tx-history/{pubkey}:
    get:
      summary: Get transaction history for a public key. Supports paging with the offsetKey and limit parameters.
      parameters:
        - name: pubkey
          description: Hex encoded public key prefixed with `0x`
          in: path
          required: true
          schema:
            $ref: 'components.yaml#/schemas/PublicKeyParam'
        - name: limit
          description: Maximum number of items response may contain
          in: query
          required: false
          schema:
            type: integer
        - name: offsetKey
          description: When doing batched queries, offset key returned by the previous query
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/cbor:
              schema:
                type: string
                format: binary
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /units/{unitId}/transactions/{txHash}/proof:
    get:
      summary: Get transaction proof by unit ID and transaction hash
      parameters:
        - name: unitId
          description: Hex encoded unit ID of the bill to get transaction proof for, prefixed with `0x`
          in: path
          required: true
          schema:
            $ref: 'components.yaml#/schemas/UnitIDParam'
        - name: txHash
          description: Hex encoded hash of the transaction to get proof for, prefixed with `0x`
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transaction proof was found
          content:
            application/cbor:
              schema:
                type: string
                format: binary
        '404':
          description: Transaction is not in the index
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/schemas/ErrorResponse'
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /fee-credit-bills/{unitId}:
    get:
      summary: Get a fee credit bill and its latest transaction proof by unit ID
      description: |-
        Returns fee credit bill for the given unit ID.
      parameters:
        - name: unitId
          description: |-
            Hex encoded free credit record ID prefixed with `0x`.
            Must be 68 characters long (including the `0x` prefix).
          in: path
          required: true
          schema:
            $ref: 'components.yaml#/schemas/UnitIDParam'
      responses:
        '200':
          description: Fee credit bill returned
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: 'components.yaml#/schemas/Bill'
        '404':
          description: Fee credit bill was not found for given unit ID
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/schemas/ErrorResponse'
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /locked-fee-credit/{systemId}/{unitId}:
    get:
      summary: Get the last transferFC transaction for the given partition and fee credit bill
      description: Get the last transferFC transaction for the given partition and fee credit bill
      parameters:
        - name: systemId
          description: Target fee credit system ID of the transferFC transaction (hex)
          in: path
          required: true
          schema:
            type: string
        - name: unitId
          description: Target fee credit bill ID (hex)
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/cbor:
              schema:
                type: string
                format: binary
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /closed-fee-credit/{unitId}:
    get:
      summary: Get the last seen closeFC transaction for the given fee credit bill
      description: Get the last seen closeFC transaction for the given fee credit bill
      parameters:
        - name: unitId
          description: Target fee credit bill ID (hex)
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/cbor:
              schema:
                type: string
                format: binary
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /transactions/{pubkey}:
    post:
      summary: Forward transactions to partition node
      description: |-
        Allows to send raw CBOR encoded transactions to partition
        node. Request body must be a CBOR encoded array of raw
        transactions. The documentation for raw transaction format can
        be found on Alphabill Documentation portal.
      parameters:
        - name: pubkey
          description: Hex encoded sender public key prefixed with `0x`
          in: path
          required: true
          schema:
            $ref: 'components.yaml#/schemas/PublicKeyParam'
      requestBody:
        description: CBOR encoded array of TransactionOrders
        required: true
        content:
          application/cbor: {}
      responses:
        '202':
          description: Successful operation
        '500':
          $ref: 'components.yaml#/responses/PostTransactionsErrorResponse'
        default:
          $ref: 'components.yaml#/responses/ErrorResponse'
  /info:
    get:
      summary: Get info about the partition
      description: |-
        Returns static info about the partition such as partition system identifier etc
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
components:
  schemas:
    BalanceResponse:
      type: object
      properties:
        balance:
          type: string
          example: '500'
    ListBillsResponse:
      type: object
      properties:
        bills:
          type: array
          items:
            $ref: 'components.yaml#/schemas/Bill'
    InfoResponse:
      type: object
      properties:
        system_id:
          type: string
          example: '00000000'
        name:
          type: string
          example: 'money backend'